import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/view/header/page";
import Providers from "@/components/providers/provider";
import Footer from "@/view/footer/page";
import  { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className="mx-16 max-lg:mx-6  mt-36 max-lg:mt-24">{children}</main>
           <Footer />
           <Toaster />
        </Providers>
          
      </body>
    </html>
  );
}
